name: Mermaid

on:
  push:
    branches: [ main ]
    paths:
      - action.yml
  workflow_dispatch:

jobs:
  mermaid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: mermaid
        uses: ./

      # Create or update an action.mermaid.md
      - name: Create or update action.mermaid.md
        env:
          MERMAID: ${{ steps.mermaid.outputs.mermaid }}
        run: |-
          echo "$MERMAID" > action.mermaid.md
          
      - name: Create or update mermaid section of README
        env:
          MERMAID: ${{ steps.mermaid.outputs.mermaid }}
        run: |-
          echo 'f = File.read("README.md")' >> script.rb
          echo 'f = f.sub(/(<!-- START MERMAID -->).*(<!-- END MERMAID -->)/im, "<!-- START MERMAID -->\n#{ENV["MERMAID"]}\n<!-- END MERMAID -->")' >> script.rb
          echo 'File.write("README.md", f, mode: "w")' >> script.rb
          ruby script.rb

      - name: Commit to action.mermaid.md
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            action.mermaid.md
            README.md
          commit-message: Update action.mermaid.md with mermaid diagram
          ref: refs/heads/main