name: Mark stale issues and pull requests

on:
  schedule:
  - cron: 55 17 10 * *
  
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@428b0ed64d74596742200dc98805bb90f39ef9f0 # v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Beep boop! ðŸ¤– This issue hasn't had any activity in a while. I'll close it if I don't hear back soon."
        stale-pr-message: "Beep boop! ðŸ¤– This pull request hasn't had any activity in a while. I'll close it if I don't hear back soon."
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-labels: 'no-stale'
        days-before-stale: 30
        days-before-close: 15
